version: 2.1

jobs: # basic units of work in a run
  build:
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: ccfciteam/ccf-app-ci:latest
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      # Run a step to setup an environment variable
      # Redirect MY_ENV_VAR into $BASH_ENV
      - run:
          name: "start"
          command: |
            apt install wget
            wget https://github.com/microsoft/CCF/releases/download/ccf-0.15.2/ccf_0.15.2_amd64.deb
            apt install ./ccf_0.15.2_amd64.deb
            cd /opt/ccf-0.15.2
            cd getting_started/setup_vm
            run.sh app-dev.yml
      