version: 2.1

jobs: # basic units of work in a run
  bar:
    machine: true
    steps:
      - checkout
      - run:
          command: echo "build"
      - run:
          command: echo "test"

workflows:
  build:
    jobs:
      - bar:
         pre-steps:
           - run:
              command: echo "install current"
         post-steps:
           - run:
              command: echo "upload"